// languageMap.js
const languageMap = {
    aa: 'Afar',
    ab: 'Аҧсуа',
    ae: 'avesta',
    af: 'Afrikaans',
    ak: 'Akan',
    am: 'አማርኛ',
    an: 'Aragonés',
    ar: 'العربية',
    as: 'অসমীয়া',
    av: 'авар мацӀ',
    ay: 'Aymar aru',
    az: 'azərbaycan dili',
    ba: 'башҡорт теле',
    be: 'беларуская мова',
    bg: 'български език',
    bh: 'भोजपुरी',
    bi: 'Bislama',
    bm: 'bamanankan',
    bn: 'বাংলা',
    bo: 'བོད་ཡིག',
    br: 'brezhoneg',
    bs: 'bosanski jezik',
    ca: 'Català',
    ce: 'нохчийн мотт',
    ch: 'Chamoru',
    co: 'Corsu',
    cr: 'ᓀᐦᐃᔭᐍᐏᐣ',
    cs: 'čeština',
    cu: 'ѩзыкъ словѣньскъ',
    cv: 'чӑваш чӗлхи',
    cy: 'Cymraeg',
    da: 'dansk',
    de: 'Deutsch',
    dv: 'ދިވެހި',
    dz: 'རྫོང་ཁ',
    ee: 'Ɛʋɛgbɛ',
    el: 'Ελληνικά',
    en: 'English',
    'en-gb': 'English (UK)',
    eo: 'Esperanto',
    es: 'Español',
    et: 'eesti',
    eu: 'euskara',
    fa: 'فارسی',
    ff: 'Fulfulde',
    fi: 'suomi',
    fj: 'Vakaviti',
    fo: 'føroyskt',
    fr: 'français',
    fy: 'Frysk',
    ga: 'Gaeilge',
    gd: 'Gàidhlig',
    gl: 'Galego',
    gn: 'Avañe\'ẽ',
    gu: 'ગુજરાતી',
    gv: 'Gaelg',
    ha: 'Hausa',
    he: 'עברית',
    hi: 'हिन्दी',
    ho: 'Hiri Motu',
    hr: 'hrvatski jezik',
    ht: 'Kreyòl ayisyen',
    hu: 'magyar',
    hy: 'հայերեն',
    hz: 'Otjiherero',
    ia: 'Interlingua',
    id: 'Bahasa Indonesia',
    ie: 'Interlingue',
    ig: 'Asụsụ Igbo',
    ii: 'ꆈꌠ꒿ Nuosuhxop',
    ik: 'Iñupiaq',
    io: 'Ido',
    is: 'Íslenska',
    it: 'italiano',
    iu: 'ᐃᓄᒃᑎᑐᑦ',
    ja: '日本語',
    jv: 'ꦧꦱꦗꦮ',
    ka: 'ქართული',
    kg: 'Kikongo',
    ki: 'Gĩkũyũ',
    kj: 'Kuanyama',
    kk: 'қазақ тілі',
    kl: 'kalaallisut',
    km: 'ខ្មែរ',
    kn: 'ಕನ್ನಡ',
    ko: '한국어',
    kr: 'Kanuri',
    ks: 'कश्मीरी',
    ku: 'Kurdî',
    kv: 'коми кыв',
    kw: 'Kernewek',
    ky: 'Кыргызча',
    la: 'latine',
    lb: 'Lëtzebuergesch',
    lg: 'Luganda',
    li: 'Limburgs',
    ln: 'Lingála',
    lo: 'ພາສາລາວ',
    lt: 'lietuvių kalba',
    lu: 'Tshiluba',
    lv: 'latviešu valoda',
    mg: 'fiteny malagasy',
    mh: 'Kajin M̧ajeļ',
    mi: 'te reo Māori',
    mk: 'македонски јазик',
    ml: 'മലയാളം',
    mn: 'монгол',
    mr: 'मराठी',
    ms: 'Bahasa Melayu',
    mt: 'Malti',
    my: 'ဗမာစာ',
    na: 'Dorerin Naoero',
    nb: 'Norsk bokmål',
    nd: 'isiNdebele',
    ne: 'नेपाली',
    ng: 'Owambo',
    nl: 'Nederlands',
    nn: 'Norsk nynorsk',
    no: 'Norsk',
    nr: 'isiNdebele',
    nv: 'Diné bizaad',
    ny: 'chiCheŵa',
    oc: 'occitan',
    oj: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
    om: 'Afaan Oromoo',
    or: 'ଓଡ଼ିଆ',
    os: 'ирон æвзаг',
    pa: 'ਪੰਜਾਬੀ',
    pi: 'पाऴि',
    pl: 'polski',
    ps: 'پښتو',
    pt: 'português',
    qu: 'Runa Simi',
    rm: 'rumantsch grischun',
    rn: 'Ikirundi',
    ro: 'Română',
    ru: 'Русский',
    rw: 'Ikinyarwanda',
    sa: 'संस्कृतम्',
    sc: 'sardu',
    sd: 'सिन्धी',
    se: 'Davvisámegiella',
    sg: 'Sängö',
    si: 'සිංහල',
    sk: 'slovenčina',
    sl: 'slovenski jezik',
    sm: 'gagana fa\'a Samoa',
    sn: 'chiShona',
    so: 'Soomaaliga',
    sq: 'Shqip',
    sr: 'српски језик',
    ss: 'SiSwati',
    st: 'Sesotho',
    su: 'Basa Sunda',
    sv: 'svenska',
    sw: 'Kiswahili',
    ta: 'தமிழ்',
    te: 'తెలుగు',
    tg: 'тоҷикӣ',
    th: 'ไทย',
    ti: 'ትግርኛ',
    tk: 'Türkmen',
    tl: 'Wikang Tagalog',
    tn: 'Setswana',
    to: 'faka Tonga',
    tr: 'Türkçe',
    ts: 'Xitsonga',
    tt: 'татар теле',
    tw: 'Twi',
    ty: 'Reo Tahiti',
    ug: 'ئۇيغۇرچە',
    uk: 'українська мова',
    ur: 'اردو',
    uz: 'Oʻzbek',
    ve: 'Tshivenḓa',
    vi: 'Tiếng Việt',
    vo: 'Volapük',
    wa: 'walon',
    wo: 'Wolof',
    xh: 'isiXhosa',
    yi: 'ייִדיש',
    yo: 'Yorùbá',
    za: 'Saɯ cueŋƅ',
    zh: '中文',
    zu: 'isiZulu'
  };
  
  module.exports = languageMap;
  