[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --no-audit --no-fund"]
dependsOn = ["setup"]

[phases.build]
cmds = ["npm run build || true"]
dependsOn = ["install"]

[start]
cmd = "node index.js --production" 