[phases.setup]
aptPkgs = ["curl"]

[phases.install]
cmds = ["npm install --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build || true"]
dependsOn = ["install"]

[start]
cmd = "node index.js --production" 